### ISSUE TITLE
Clojure symbols that start with "def" are colored the same as def/defn

### ISSUE THREAD

**Issue by ian-moore** [sssmi/after-dark#1]
First off, thanks for this theme. I am not a huge fan of the cursive (which doesn't show up for me since I lack the font) or the italics but it's the first theme I've found for VS Code that actually does Clojure syntax highlighting correctly. I found a minor bug where things that start "def" are colored incorrectly, which is a bit distracting.

![image](https://user-images.githubusercontent.com/1709416/46040623-6f70d500-c0d6-11e8-90b7-00b92d232c2f.png)

**Comment by sssmi** [comment]
Hi! Thank for the feedback and glad to hear you have enjoyed using this theme! 🙏
Unfortunately Clojure language highlighting in VS Code is not as extensive as it is for example in emacs.
The issue here is what regular expressions are used to match the syntax to scopes, and as you pointed out, VS Code matches _any_ word starting ```def``` with the keyword.control scope.
